---

computername: Default # friendly name for Bonjour
hostname: default-mbp

finder_proxy_icon_hover_delay: 0
finder_show_file_extensions_warning: yes
finder_warn_before_emptying_the_trash: yes
finder_show_statusbar: no
finder_show_hdd_desktop: no
finder_show_mounts_desktop: no
finder_new_window_target: file:///path/to/folder

dock_make_hidden_apps_translucent: no
dock_show_indicator_lights_for_open_apps: yes
dock_mc_mruspaces: yes
dock_mb_bt: no
dock_mb_airplay: no
dock_mb_nowplaying: no
dock_mb_sound: no
dock_mb_spotlight: no
dock_mb_clock: "EEE MMM d  j:mm a" # Clock format, default ex. Wed Jul 17 10:16 AM

safari_show_full_url_in_address_bar: yes
safari_open_safe_files_automatically: yes
safari_show_status_bar: yes
safari_show_developer_menu: yes
safari_show_debug_menu: no
safari_show_webinspector: yes
safari_enable_webkit_extras: yes
safari_enable_donottrack: yes
safari_sha1_crt_insecure: yes

system_prefer_tabs: never # (never, fullscreen or always)
system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
system_volume_feedback_sound: yes
system_startup_sound: "%00" # Either %00 or %01

trackpad_tap_to_click: yes
trackpad_rightclick: yes # tap with two fingers, set to no for next option
trackpad_rightclick_behavior: # 0=off, 1= bottom left corner, 2=bottom right corner
trackpad_naturalscroll: yes
trackpad_appexpose: no

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5
security_home_sharing: no
security_airdrop_visibility: Everyone # Everyone, Contacts Only, or Off

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jeromegamez/formulae
  - github/gh
  - aws/tap

homebrew_apps:
  - aws-vault
  - docker
  - fliqlo
  - font-fira-code
  - gpg-suite
  - iterm2
  - slack
  - spotify
  - telegram

homebrew_packages:
  - aws-shell
  - aws-sam-cli
  - chag
  - composer
  - curl
  - fasd
  - gh
  - httpie
  - imagemagick
  - jq
  - node
  - php
  - pkg-config
  - python
  - tree
  - vim

macports_packages:
  - awscli
  - git
  - emacs
  - python
  - bash
  - kerberos5
  - openssl
  - wget

mas_apps:
  - { name: Developer, id: 640199958 }
  - { name: Keynote, id: 409183694 }
  - { name: Remote Desktop, id: 409907375 }
  - { name: GarageBand, id:682658836 }
  - { name: Numbers, id:409203825 }
  - { name: Speedtest, id:1153157709 }
  - { name: Pages, id:409201541 }
  - { name: iMovie, id: 408981434 }
