---

computername: Kerngehäuse
hostname: kerngehaeuse

finder_proxy_icon_hover_delay: 0

safari_show_full_url_in_address_bar: true
safari_open_safe_files_automatically: true
safari_show_status_bar: true
safari_show_developer_menu: true

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jeromegamez/formulae
  - github/gh
  - aws/tap

homebrew_apps:
  - 1password
  - alfred
  - aws-vault
  - bartender
  - brave-browser
  - cardhop
  - cleanmymac
  - dash
  - discord
  - docker
  - fantastical
  - firefox
  - fliqlo
  - font-fira-code
  - gpg-suite
  - iterm2
  - jetbrains-toolbox
  - mailmate
  - multimc
  - paw
  - sequel-pro
  - sonos
  - spillo
  - slack
  - spotify
  - sublime-merge
  - sublime-text
  - tableplus
  - telegram
  - transmit
  - twitch
  - whatsapp

homebrew_packages:
  - aws-shell
  - awscli
  - aws-sam-cli
  - bash
  - chag
  - composer
  - curl
  - fasd
  - gh
  - git
  - httpie
  - imagemagick
  - jq
  - make
  - node
  - openssh
  - php
  - pkg-config
  - python
  - tree
  - vim
  - wget
  - yadm
  - watch
  - zlib
  - zsh

mas_apps:
  - { name: 1Blocker, id: 1107421413 }
  - { name: Bear, id: 1091189122 }
  - { name: Pages, id: 409201541 }
  - { name: Patterns, id: 429449079 }
  - { name: Tweetbot, id: 1384080005 }
