---

- name: Update Macports and the ports tree
  community.general.macports:
    selfupdate: yes
  become: yes

- name: Install a list of ports
  community.general.macports:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    variant: "{{ item.variant | default(omit) }}"
  loop: "{{ macports_packages }}"
  when: macports_packages|default([])|count > 0
  become: yes
