---

- name: Install non-App Store apps
  shell: "{{role_path}}/files/macapps.sh"
  args:
    chdir: "{{role_path}}"
    executable: /bin/bash
  register: shellout
  become: yes

- debug: var=shellout.stdout
