---

- name: Make Dock icons of hidden applications translucent.
  when: dock_make_hidden_apps_translucent != None
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: "{{ dock_make_hidden_apps_translucent|bool }}"
  notify: Restart Dock

- name: Show indicator lights for open applications in the Dock.
  when: dock_show_indicator_lights_for_open_apps != None
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: "{{ dock_show_indicator_lights_for_open_apps|bool }}"
  notify: Restart Dock
