---

- name: "Show full URL in the address bar ({{ show_full_url_in_address_bar }})"
  when: safari_show_full_url_in_address_bar != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: ShowFullURLInSmartSearchField
    type: bool
    value: "{{ safari_show_full_url_in_address_bar }}"
  notify: Restart Safari

- name: "Open 'safe' files automatically ({{ open_safe_files_automatically }})"
  when: safari_open_safe_files_automatically != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: AutoOpenSafeDownloads
    type: bool
    value: "{{ safari_open_safe_files_automatically }}"
  notify: Restart Safari

- name: "Show status bar ({{ show_status_bar }})"
  when: safari_show_status_bar != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: ShowOverlayStatusBar
    type: bool
    value: "{{ safari_show_status_bar }}"
  notify: Restart Safari

- name: "Show Developer menu ({{ show_developer_menu }})"
  when: safari_show_developer_menu != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: IncludeDevelopMenu
    type: bool
    value: "{{ safari_show_developer_menu|bool }}"
  notify: Restart Safari

- name: "Enable Debug menu ({{ show_debug_menu }})"
  when: safari_show_debug_menu != None
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: "{{ safari_show_debug_menu|bool }}"
  notify: Restart Safari

- name: "Enable Web Inspector ({{ show_webinspector }})"
  when: safari_show_webinspector != None
  osx_defaults:
    - domain: com.apple.Safari
      key: WebKitDeveloperExtrasEnabledPreferenceKey
      type: bool
      value: "{{ safari_show_webinspector|bool }}"
    - domain: NSGlobalDomain
      key: WebKitDeveloperExtras
      type: bool
      value: "{{ safari_show_webinspector|bool }}"
  notify: Restart Safari

- name: "Enable WebKit Extras ({{ enable_webkit_extras }})"
  when: safari_enable_webkit_extras != None
  osx_defaults:
    domain: com.apple.Safari
    key: ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
    type: bool
    value: "{{ safari_enable_webkit_extras|bool }}"
  notify: Restart Safari

- name: "Send DNT header ({{ enable_donottrack }})"
  when: safari_enable_donottrack != None
  osx_defaults:
    domain: com.apple.Safari
    key: SendDoNotTrackHTTPHeader
    type: bool
    value: "{{ safari_enable_donottrack|bool }}"
  notify: Restart Safari

- name: "Treat SHA-1 certificates as insecure ({{ safari_sha1_crt_insecure }})"
  when: safari_sha1_crt_insecure != None
  osx_defaults:
    domain: com.apple.Safari
    key: TreatSHA1CertificatesAsInsecure
    type: bool
    value: "{{ safari_sha1_crt_insecure|bool }}"
  notify: Restart Safari

