---

- name: Save application states on quit ({{ save_application_state_on_quit }})
  when: save_application_state_on_quit != None
  osx_defaults:
    domain: NSGlobalDomain
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: "({{ system_save_application_state_on_quit|bool }})"

- name: Prefer tabs when opening documents ({{ system_prefer_tabs }})
  when: system_prefer_tabs != None
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleWindowTabbingMode
    type: string
    value: "({{ system_prefer_tabs }})"

- name: Expand save panel by default ({{ system_expand_save_panel_by_default }})
  when: system_expand_save_panel_by_default != None
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "{{ system_expand_save_panel_by_default|bool }}"
  notify: Restart Finder

- name: Expand print panel by default ({{ system_expand_print_panel_by_default }})
  when: system_expand_print_panel_by_default != None
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: "{{ system_expand_print_panel_by_default|bool }}"
  notify: Restart Finder

- name: Use F keys as standard function keys ({{ system_use_f_keys_as_standard_function_keys }})
  when: system_use_f_keys_as_standard_function_keys != None
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: int
    value: "{{ system_use_f_keys_as_standard_function_keys|int }}"

- name: Index network storage with Spotlight ({{ system_index_network_storage_with_spotlight }})
  become: true
  when: system_index_network_storage_with_spotlight != None
  osx_defaults:
    domain: /Library/Preferences/com.apple.SpotlightServer.plist
    key: ExternalVolumesIgnore
    type: bool
    value: "{{ system_index_network_storage_with_spotlight|bool }}"

- name: Play sound on volume change  ({{ system_volume_feedback_sound }})
  become: true
  when: system_volume_feedback_sound != None
  osx_defaults:
    - domain: "Apple Global Domain"
      key: com.apple.sound.beep.feedback
      type: bool
      value: "{{ system_volume_feedback_sound|bool }}"
    - domain: "Apple Global Domain"
      key: com.apple.sound.uiaudio.enabled
      type: bool
      value: "{{ system_volume_feedback_sound|bool }}"

- name: Get startup sound status
  become: true
  when: system_startup_sound != None
  shell: nvram StartupMute
  register: StartupMute_result
  changed_when: false
  failed_when: false
  check_mode: no

- name: Play startup sound ({{ system_startup_sound }})
  shell: nvram StartupMute="{{ system_startup_sound }}"
  become: true
  when: system_startup_sound != None and (StartupMute_result.failed or (system_startup_sound not in StartupMute_result.stdout))
